import os
import sys
import pytest
from unittest.mock import MagicMock


# NO EMAIL ONLY

# NO API KEY ONLY

# NO CREDENTIALS SUPPLIED

# WRONG EMAIL ADDRESS (RIGHT EMAIL FORMAT)

# WRONG EMAIL ADDRESS INPUT (COMPLETELY WRONG INPUT)

# WRONG API KEY

# BOTH WRONG

# BOTH VALID - NO SPECIES INPUT

# BOTH VALID - SPECIES INPUT - DEFAULT DATA

# BOTH VALID - SPECIES INPUT - CUSTOM DATA INPUT

# SPECIES NOT SUPPLIED

# WRONG SPECIES SUPPLIED ONLY

# TESTING ALL SYNONYMS FOR SPECIES IN ONE INPUT